### ISSUE TITLE
Support for tsc watch

### ISSUE THREAD

**Issue by mgorniew** [vbauer/lein-typescript#1]
Please add support for tsc watch option. With watch and lein-pdo plugin it would be easy to start ring server with typescript reload on save.

**Comment by vbauer** [comment]
@mgorniew Hello, I've just added `:watch` option. Could you please try to check it, does it work for you?

**Comment by mgorniew** [comment]
I've checked new option and it works great. Thanks.

**Comment by vbauer** [comment]
NP. :) Thank you for idea.

**Comment by vbauer** [comment]
I've just released lein-typescript-0.1.2 with this feature.
